<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>SVGToolsShell</AssemblyName>
    <RootNamespace>SVGToolsShell</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Optimize>true</Optimize>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpShell" Version="2.7.2" />
  </ItemGroup>
</Project>
